all: lab10a lab10b lab10c

lab10a: lab10a.c
	gcc lab10a.c -o lab10a -Wall -ansi
	
lab10b: lab10b.c
	gcc lab10b.c -o lab10b -Wall -ansi
	
lab10c: lab10c.c
	gcc lab10c.c -o lab10c -Wall -ansi
	
clean:
	rm lab10a
	rm lab10b
	rm lab10c